base:
  NUMBER_OF_PROCESSES: 4

agent:
  -  id: lvs_master
     adminIp: 192.168.43.144
     lvsLocalIp: 192.168.43.144
     cluster: bj_lvs_cluster
     area: beijing
     port: 60090
     state: master
  -  id: lvs_slave
     adminIp: 192.168.43.145
     lvsLocalIp: 192.168.43.145
     cluster: bj_lvs_cluster
     area: beijing
     port: 60090
     state: slave

cluster:
  - id: bj_lvs_cluster
    area: beijing
    descript: 北京LVS集群
    agent: ['lvs_master','lvs_slave']
    admin_mail_group: ['thewayma@163.com']
    manager_user: ['thewayma']

7nginxCluster:
    idc: [bj_nginx_cluster]
    etcdIp: [192.168.40.139, 192.168.40.140, 192.168.40.141]
