base:
  NUMBER_OF_PROCESSES: 4

agent:
  -  id: 10.58.95.75-lvs-master-node
     adminIp: 10.58.95.75
     lvsLocalIp: 101.226.227.165
     cluster: sh_lvs_cluster
     area: shanghai
     port: 60090
     state: master

  -  id: 10.58.95.85-lvs-slave-node
     adminIp: 10.58.95.85
     lvsLocalIp: 101.226.227.167
     cluster: sh_lvs_cluster
     area: shanghai
     port: 60090
     state: slave

cluster:
  - id: sh_lvs_cluster
    area: shanghai
    descript: 上海青浦机房 LVS集群
    agent: ['10.58.95.75-lvs-master-node','10.58.95.85-lvs-slave-node']
    admin_mail_group: ['thewayma@163.com']
    manager_user: ['thewayma']
